// Open Library enrichment (generated by `npm run enrich` into
// src/data/enrichment.json): page counts, subjects, and edition languages
// per book, looked up by the same title|author key the comparison uses.
import enrichmentData from "../data/enrichment.json";
import { matchKey } from "./compare";
import { getReadBooks } from "./library";

export interface Enrichment {
  title: string;
  author: string;
  found: boolean;
  olKey?: string;
  pages?: number;
  subjects?: string[];
  languages?: string[];
  firstPublishYear?: number;
}

const table = enrichmentData as Record<string, Enrichment>;

export function getEnrichment(title: string, author: string): Enrichment | undefined {
  const e = table[matchKey(title, author)];
  return e?.found ? e : undefined;
}

// Open Library subject strings are near-duplicates of each other ("Fiction /
// Literary", "Literary", "Literary fiction"…). Fold them into one label, and
// drop the catalog noise the fetch-side filter didn't catch.
const SUBJECT_DROP = new Set([
  "general",
  "romans, nouvelles",
  "nouvelles",
  "translations into english",
  "language and languages",
]);
const SUBJECT_CANON: Record<string, string> = {
  literary: "literary fiction",
  psychological: "psychological fiction",
  "psychological fiction": "psychological fiction",
  historical: "historical fiction",
  "historical fiction": "historical fiction",
  "science fiction": "science fiction",
  "man-woman relationships": "relationships",
  "interpersonal relations": "relationships",
  "family life": "family life",
  "domestic fiction": "family life",
};

function normalizeSubject(raw: string): string | null {
  let t = raw.toLowerCase().trim();
  // "Fiction / Literary" and "Fiction, psychological" → "literary" / "psychological"
  t = t.replace(/^fiction\s*[/,]\s*/, "").replace(/\s*[/,]\s*fiction$/, "");
  if (!t || SUBJECT_DROP.has(t)) return null;
  return SUBJECT_CANON[t] ?? t;
}

export interface SubjectCount {
  subject: string; // display label, e.g. "Literary fiction"
  count: number;
}

// The library's most common subjects — every read book's (deduped, folded)
// subjects tallied up. Only subjects shared by 2+ books are interesting.
export async function getSubjectBreakdown(limit = 14): Promise<SubjectCount[]> {
  const counts = new Map<string, number>();
  for (const b of await getReadBooks()) {
    const e = getEnrichment(b.title, b.author);
    if (!e?.subjects) continue;
    const perBook = new Set(
      e.subjects.map(normalizeSubject).filter((s): s is string => s !== null)
    );
    for (const s of perBook) counts.set(s, (counts.get(s) ?? 0) + 1);
  }
  return [...counts.entries()]
    .filter(([, count]) => count >= 2)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([subject, count]) => ({
      subject: subject.charAt(0).toUpperCase() + subject.slice(1),
      count,
    }));
}
