// Open Library enrichment (generated by `npm run enrich` into
// src/data/enrichment.json): page counts, subjects, and edition languages
// per book, looked up by the same title|author key the comparison uses.
import enrichmentData from "../data/enrichment.json";
import { matchKey } from "./compare";
import { getReadBooks } from "./library";

export interface Enrichment {
  title: string;
  author: string;
  found: boolean;
  olKey?: string;
  pages?: number;
  subjects?: string[];
  languages?: string[];
  firstPublishYear?: number;
}

const table = enrichmentData as Record<string, Enrichment>;

export function getEnrichment(title: string, author: string): Enrichment | undefined {
  const e = table[matchKey(title, author)];
  return e?.found ? e : undefined;
}

// Open Library subject strings are near-duplicates of each other ("Fiction /
// Literary", "Literary", "Literary fiction"…). Fold them into one label, and
// drop the catalog noise the fetch-side filter didn't catch.
const SUBJECT_DROP = new Set([
  "general",
  "romans, nouvelles",
  "nouvelles",
  "translations into english",
  "language and languages",
]);
const SUBJECT_CANON: Record<string, string> = {
  literary: "literary fiction",
  psychological: "psychological fiction",
  "psychological fiction": "psychological fiction",
  historical: "historical fiction",
  "historical fiction": "historical fiction",
  "science fiction": "science fiction",
  "man-woman relationships": "relationships",
  "interpersonal relations": "relationships",
  "family life": "family life",
  "domestic fiction": "family life",
  // Two labels, one shelf — Open Library uses both, heavily, on the same books.
  "juvenile fiction": "children's fiction",
  "children's fiction": "children's fiction",
  "fantasy fiction": "fantasy",
  fantasy: "fantasy",
  // Inverted spellings of a sub-genre. Folded onto each other, but kept
  // distinct from the parent genre — "contemporary romance" is a real
  // narrowing of "romance", not a synonym for it.
  "romance, contemporary": "contemporary romance",
  "contemporary romance": "contemporary romance",
  "fantasy, epic": "epic fantasy",
  "epic fantasy": "epic fantasy",
};

function normalizeSubject(raw: string): string | null {
  let t = raw.toLowerCase().trim();
  // "Fiction / Literary" and "Fiction, psychological" → "literary" / "psychological"
  t = t.replace(/^fiction\s*[/,]\s*/, "").replace(/\s*[/,]\s*fiction$/, "");
  // A cataloging suffix carrying no meaning of its own: "Romance, general" and
  // "Science fiction, general" are just "romance" and "science fiction".
  t = t.replace(/\s*,\s*general$/, "");
  if (!t || SUBJECT_DROP.has(t)) return null;
  return SUBJECT_CANON[t] ?? t;
}

// The shape a subject chart needs from whatever shelf it's built over — the
// owner's ReadEntry satisfies it as-is; a friend's book is mapped onto it.
export interface SubjectBook {
  title: string;
  author: string;
  rating: number;
  cover?: string;
  href?: string;
  external?: boolean; // true = links out to Goodreads
}

export interface SubjectCount {
  subject: string; // display label, e.g. "Literary fiction"
  count: number;
  books: SubjectBook[]; // the books behind the bar, best-rated first
}

// A shelf's most common subjects — every book's (deduped, folded) subjects
// tallied up. Only subjects shared by 2+ books are interesting. Books are
// deduped by match key first, since a friend can shelve the same book twice.
// Each subject keeps its own books so the chart can unfold them on click;
// `count` is therefore always `books.length`.
export function subjectBreakdown(
  books: readonly SubjectBook[],
  limit = 14
): SubjectCount[] {
  const bySubject = new Map<string, SubjectBook[]>();
  const seen = new Set<string>();
  for (const b of books) {
    const key = matchKey(b.title, b.author);
    if (seen.has(key)) continue;
    seen.add(key);
    const e = getEnrichment(b.title, b.author);
    if (!e?.subjects) continue;
    const perBook = new Set(
      e.subjects.map(normalizeSubject).filter((s): s is string => s !== null)
    );
    for (const s of perBook) {
      const list = bySubject.get(s);
      if (list) list.push(b);
      else bySubject.set(s, [b]);
    }
  }
  return [...bySubject.entries()]
    .filter(([, list]) => list.length >= 2)
    .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([subject, list]) => ({
      subject: subject.charAt(0).toUpperCase() + subject.slice(1),
      count: list.length,
      books: list
        .slice()
        .sort((x, y) => y.rating - x.rating || x.title.localeCompare(y.title)),
    }));
}

// The owner's library, for /stats. Friends' shelves go through
// subjectBreakdown() directly from /friends/<slug>.
export async function getSubjectBreakdown(limit = 14): Promise<SubjectCount[]> {
  return subjectBreakdown(await getReadBooks(), limit);
}
